spring:
  datasource:
    url: jdbc:h2:mem:brokerage-local;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

# For actuator if you enable it later:
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
